CapLink/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.project.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('project/', include('apps.project.urls')),
    path('contact/', include('apps.contact.urls')),
    path("games/", include("apps.games.urls")),
    path('', IndexView.as_view(), name='index'),

    # mdeditor
    path(r'mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/games/urls.py
from django.urls import path

from . import views


app_name = "games"

urlpatterns = [
    path("gameList/", views.GameListView.as_view(), name="game-list"),
    path("detail/<slug:pk>/", views.GameDetailView.as_view(), name="detail")
]

apps/games/models.py
from django.db import models
from django.urls import reverse
from mdeditor.fields import MDTextField


# Create your models here.


class GameTag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "游戏标签"
        verbose_name_plural = verbose_name


class Game(models.Model):
    name = models.CharField(max_length=255)
    description = MDTextField()
    disclaimer = MDTextField()
    tags = models.ManyToManyField(GameTag)
    short_desc = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse("games:detail", kwargs={"pk": self.pk})

    @property
    def main_img(self):
        return self.gameimg_set.filter(main=True).first()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "游戏"
        verbose_name_plural = verbose_name


class Action(models.Model):
    text = models.CharField(max_length=255)
    url = models.TextField(max_length=255)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.game.name

    class Meta:
        verbose_name = "动作"
        verbose_name_plural = verbose_name


class GameImg(models.Model):
    img = models.ImageField(upload_to="gameimages")
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    main = models.BooleanField(default=False)

    def __str__(self):
        return self.game.name

    class Meta:
        verbose_name = "游戏图片"
        verbose_name_plural = verbose_name


class Faq(models.Model):
    question = models.TextField()
    answer = models.TextField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = "faq"
        verbose_name_plural = verbose_name


"""
text
url
"""

apps/games/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Game, GameTag

# Create your views here.


class GameDetailView(DetailView):
    model = Game
    template_name = "frontend/games/detail.html"


class GameListView(ListView):
    model = Game
    template_name = "frontend/games/game-list.html"
    extra_context = {"tags": GameTag.objects.all()}

templates/frontend/games/detail.html
{% extends 'frontend/base.html' %}
{% load markdown %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block css %}
<style>
    .product-table {
        background-color: #f7f7f7;
    }
</style>
{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="py-1 my-2 breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Games</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.title }}</li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<section class="sidebar-end border-bottom mb-5 mb-md-6">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 content py-4">
                <!-- Product gallery-->
                <div class="product-gallery">
                    <div class="product-gallery-preview order-sm-2">
                        <div class="product-gallery-preview-item active" id="first"><img src="{{ object.main_img.img.url }}" alt="Product preview"></div>
                    </div>
                </div>
            </div>
            <!-- Product info-->
            <div class="col-lg-3 pt-5 ps-lg-4 pb-md-2">
                <div class="ps-lg-4 pb-5">
                    <h2 class="mb-3 pb-4">{{ object.name }}</h2>
                    <div class="mt-4 mb-3">
                        {% for tag in object.tags.all %}<span class="badge bg-success" style="margin-right: 5px">{{ tag }}</span>{% endfor %} <br><br>
                        {{ object.short_desc }}
                    </div>
                    <div class="mt-4 mb-3" style="margin-top: 20px">
                        {% for action in object.action_set.all %}
                            <a class="btn btn-primary d-block w-100" href="{{ action.url }}">{{ action.text }}</a>
                            <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h3>Detail</h3>
            <hr>
            {{ object.description|md2html|safe }}
        </div>
        <div class="row" style="margin-top: 30px">
            <h3>FAQ</h3>
            <hr>
            <!-- Flush accordion. Use this when you need to render accordions edge-to-edge with their parent container -->
            <div class="accordion accordion-flush" id="accordionFlushExample">
            {% for faq in object.faq_set.all %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{ faq.pk }}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ faq.pk }}" aria-expanded="false" aria-controls="collapse{{ faq.pk }}">{{ faq.question }}</button>
                    </h2>
                    <div class="accordion-collapse collapse" id="collapse{{ faq.pk }}" aria-labelledby="heading{{ faq.pk }}" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">{{ faq.answer }}</div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>

        <div class="row" style="margin-top: 30px">
            <h3>Disclaimers</h3>
            <hr>
            <p>{{ object.disclaimer|md2html|safe }}</p>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/games/game-list.html
{% extends 'frontend/base.html' %}

{% block title %}
Projects
{% endblock %}

{% block content %}
<section class="position-relative bg-dark pt-7 pb-5 pb-md-7 bg-size-cover bg-attachment-fixed" style="background-image: url(img/demo/web-studio/cubes-bg.jpg);">
    <div class="shape shape-bottom shape-curve bg-body">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3000 185.4">
            <path fill="currentColor" d="M3000,0v185.4H0V0c496.4,115.6,996.4,173.4,1500,173.4S2503.6,115.6,3000,0z"></path>
        </svg>
    </div>
    <div class="container position-relative zindex-5 text-center pt-md-6 pt-lg-7 py-5 my-lg-3">
        <h1 class="text-light mb-0">List of Games</h1>
    </div>
</section>
<!-- Portfolio grid-->
<section class="container overflow-hidden py-5 py-md-6 py-lg-7">
    <div class="masonry-filterable pt-3 pt-md-0">
        <ul class="masonry-filters nav nav-tabs justify-content-center pb-4">
            <li class="nav-item"><a class="nav-link active" href="#" data-group="all">All</a></li>
            {% for tag in tags %}
                <li class="nav-item"><a class="nav-link" href="#" data-group="{{ tag.pk }}">{{ tag.name }}</a></li>
            {% endfor %}
        </ul>

            <div class="masonry-grid" data-columns="3">
            {% for game in object_list %}
                <div class="masonry-grid-item" data-groups="[&quot;{% for tag in game.tags.all %}{{ tag.pk }},{% endfor %}&quot;]"><a class="card card-hover border-0 shadow" href="{{ game.get_absolute_url }}"><img class="card-img-top" src="{{ game.main_img.img.url }}" alt="img">
                    <div class="card-body text-center">
                        <h3 class="h5 nav-heading mb-2">{{ game.name }}</h3>
{#                        <p class="fs-sm text-muted mb-2">{{ game.short_desc }}</p>#}
                    </div></a>
                </div>
            {% endfor %}
            </div>

    </div>
</section>

<script src="/static/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
<script src="/static/vendor/shufflejs/dist/shuffle.min.js"></script>
{% endblock %}