CapLink/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.project.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('project/', include('apps.project.urls')),
    path('contact/', include('apps.contact.urls')),
    path("games/", include("apps.games.urls")),
    path('', IndexView.as_view(), name='index'),

    # mdeditor
    path(r'mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/urls.py
from django.urls import path

from . import views


app_name = 'user'


urlpatterns = [
    path('login/', views.LoginAPIView.as_view(), name='login'),
    path('register/', views.RegisterAPIView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('identitycertification/', views.IdentityCertificationView.as_view(), name='identitycertification'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard')
]

apps/order/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.


class Order(models.Model):
    STATUS_CHOICES = (
        ('normal', 'normal'),
        ('repair', 'repair'),
        ('waiting', 'waiting'),
        )

    order_id = models.UUIDField(default=uuid4, unique=True)
    service_product = models.CharField(max_length=255)
    pool = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    longth = models.IntegerField(validators=(MinValueValidator(0),))
    output = models.DecimalField(max_digits=9, decimal_places=4)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10)

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.order_id)

    @property
    def residual_time(self):
        pass

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'orders'


class Output(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='production')

    date = models.CharField(max_length=255)
    pool = models.CharField(max_length=255)
    production = models.DecimalField(max_digits=9, decimal_places=4)

    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.date

apps/user/models.py
from django.db import models
from django.contrib.auth.views import get_user_model
from django.conf import settings

# Create your models here.


class AMl(models.Model):
    COUNTRY_CHOICES = (
        ('USA', 'USA'),
        ('CHINA', 'CHINA')
    )

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    country = models.CharField(max_length=255, choices=COUNTRY_CHOICES)
    address = models.CharField(max_length=255)
    post_code = models.IntegerField()

    identification = models.FileField()
    address_proof = models.FileField()

    is_success = models.BooleanField(default=False)

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

apps/user/forms.py
from django import forms

from .models import AMl


class IdentityCertificationForm(forms.ModelForm):
    class Meta:
        model = AMl
        exclude = ('user', )

apps/user/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import get_user_model
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView
from rest_framework.response import Response
from rest_framework.views import APIView
from django.core.exceptions import PermissionDenied

from .serializers import LoginSerializer, RegisterSerializer
from .forms import IdentityCertificationForm

# Create your views here.


class LoginAPIView(APIView):
    def post(self, request, *args, **kwargs):
        ser = LoginSerializer(data=request.data)
        if ser.is_valid():
            user = authenticate(**ser.validated_data)
            if user is not None:
                login(request, user)
                return Response(data={
                    'code': 0,
                    'msg': 'ok',
                    'data': {}
                })
            return Response(data={
                'code': -1,
                'msg': 'username or password does not exist',
                'data': {}
            })
        return Response(data=ser.errors)


class RegisterAPIView(APIView):
    def post(self, request, *args, **kwargs):
        ser = RegisterSerializer(data=request.data)
        if ser.is_valid():
            data = ser.validated_data
            username = data['username']
            try:
                get_user_model().objects.get(username=username)
            except get_user_model().DoesNotExist:
                user = get_user_model().objects.create_user(username)
                user.set_password(data['password'])
                user.email = data['email']
                user.first_name = data['fullname']
                user.save()
                return Response(data={
                    'code': 0,
                    'msg': 'ok',
                    'data': {}
                })
            return Response(data={
                'code': -1,
                'msg': 'username existed',
                'data': {}
            })

        return Response(data=ser.errors)


class IdentityCertificationView(FormView):
    form_class = IdentityCertificationForm
    template_name = 'frontend/user/identitycertification.html'
    success_url = reverse_lazy('user:identitycertification')

    def form_valid(self, form):
        if hasattr(self.request.user, 'aml'):
            raise PermissionDenied
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()

        return super(IdentityCertificationView, self).form_valid(form)


class DashboardView(TemplateView):
    template_name = 'frontend/user/dashboard.html'

templates/frontend/user/dashboard.html
{% extends 'frontend/base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="py-1 my-2 breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
{#{% include 'frontend/components/sidebar.html' %}#}
<!-- Page content-->
<!-- Slanted background-->
<div class="position-relative bg-gradient" style="height: 480px;">
    <div class="shape shape-bottom shape-slant bg-secondary d-none d-lg-block">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3000 260">
            <polygon fill="currentColor" points="0,257 0,260 3000,260 3000,0"></polygon>
        </svg>
    </div>
</div>
<!-- Page content-->
<div class="container position-relative zindex-5 pb-4 mb-md-3" style="margin-top: -350px;">
    <div class="row">
        <!-- Sidebar-->
        {% include 'frontend/components/sidebar.html' %}
        <!-- Content-->
        <div class="col-lg-8">
            <div class="d-flex flex-column h-100 bg-light rounded-3 shadow-lg p-4">
                <div class="pt-2 p-md-3">
                    <!-- Title-->
                    <h1 class="h3 mb-3 pb-2 text-center text-sm-start">Dashboard</h1>
                    <!-- Stats-->
                    <div class="row mx-n2 py-2">
                        <div class="col-md-6 col-sm-6 px-2 mb-3">
                            <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                                <h3 class="fs-sm fw-medium text-body">Cash Balance</h3>
                                <p class="h2 mb-2">$00.00</p>
                                <p class="fs-ms text-muted mb-0">As of today</p>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 px-2 mb-3">
                            <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                                <h3 class="fs-sm fw-medium text-body">Crypto Balance</h3>
                                <p class="h2 mb-2">$00.00</p>
                                <p class="fs-ms text-muted mb-0">As of today</p>
                            </div>
                        </div>
                    </div>
                    <!-- Orders -->
                    <div class="row mx-n2 pt-2">
                        <div class="col-md-12 px-2">
                            <div class="card mb-4">
                            <div class="card-body">
                                <h5 class=" pb-3 mb-3 border-bottom" style="">NFTs </h5>
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
{#                                            <tr>#}
{#                                                <th>Order Number</th>#}
{#                                                <th>Service Product</th>#}
{#                                                <th>Mining Pool</th>#}
{#                                                <th>Residual Time</th>#}
{#                                                <th>Accumulated Output</th>#}
{#                                                <th>Current Status</th>#}
{#                                                <th>Next Operation</th>#}
{#                                            </tr>#}
                                        </thead>
                                        <tbody>
{#                                            {% for order in request.user.order_set.all %}#}
{#                                                <tr>#}
{#                                                    <td>{{ order.order_id }}</td>#}
{#                                                    <td>{{ order.service_product }}</td>#}
{#                                                    <td>{{ order.pool }}</td>#}
{#                                                    <td></td>#}
{#                                                    <td>{{ order.output }}</td>#}
{#                                                    <td>{{ order.status }}</td>#}
{#                                                    <td><button class="btn btn-sm btn-primary">View more</button></td>#}
{#                                                </tr>#}
{#                                            {% endfor %}#}
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/frontend/user/identitycertification.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Identity Certification
{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="py-1 my-2 breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Identity Certification</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-bottom: 30px">
    <!-- Sidebar-->
    {% include 'frontend/components/sidebar.html' %}
    <!-- Content-->
    <div class="col-lg-8">
            <div class="d-flex flex-column h-100 bg-light rounded-3 shadow-lg p-4">
                <div class="py-2 p-md-3">
                    <!-- Title + Delete link-->
                    <div class="d-sm-flex align-items-center justify-content-between pb-4 text-center text-sm-start">
                        <h1 class="h3 mb-2 text-nowrap">Identity Certification</h1>
                    </div>
                    {% if not request.user.aml %}
                        {{ form.errors }}
                        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="mb-3 pb-1">
                                    {{ form.first_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb-3 pb-1">
                                    {{ form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="mb-3 pb-1">
                                    {{ form.country|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="mb-3 pb-1">
                                    {{ form.address|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="mb-3 pb-1">
                                    {{ form.post_code|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb-3 pb-1">
                                    {{ form.identification|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb-3 pb-1">
                                    {{ form.address_proof|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-12">
                                <hr class="mt-2 mb-4">
                                <div class="d-flex flex-wrap justify-content-between align-items-center">
                                    <button class="btn btn-primary mt-3 mt-sm-0" type="submit"><i class="ai-save fs-lg me-2"></i>Submission</button>
                                </div>
                            </div>
                        </div>
                    </form>
                {% else %}
                    <!-- Primary alert -->
                    <div class="alert alert-success" role="alert">
                        <h4 class="pt-2 alert-heading">Well done!</h4>
                        <p>Dear Sir or Madam,</p>
                        <p>Please wait until our assistants review your information and uploaded docs. We will keep you updated with further information and decision.</p>
                        <p>Thanks for your support for Pernova!<br>Pernova.eth</p>
                        <p class="mb-2"></p>
                    </div>
                {% endif %}
                </div>
            </div>
    </div>
</div>
</div>
{% endblock %}