CapLink/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.project.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('project/', include('apps.project.urls')),
    path('contact/', include('apps.contact.urls')),
    path("games/", include("apps.games.urls")),
    path('', IndexView.as_view(), name='index'),

    # mdeditor
    path(r'mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contact/urls.py
from django.urls import path

from . import views


app_name = 'contact'


urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about')
]

apps/games/urls.py
from django.urls import path

from . import views


app_name = "games"

urlpatterns = [
    path("gameList/", views.GameListView.as_view(), name="game-list"),
    path("detail/<slug:pk>/", views.GameDetailView.as_view(), name="detail")
]

apps/user/urls.py
from django.urls import path

from . import views


app_name = 'user'


urlpatterns = [
    path('login/', views.LoginAPIView.as_view(), name='login'),
    path('register/', views.RegisterAPIView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('identitycertification/', views.IdentityCertificationView.as_view(), name='identitycertification'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard')
]

templates/frontend/components/footer.html
<footer class="footer bg-dark pt-5 pt-md-6">
    <div class="container pt-3 pb-0 pt-md-0 pb-md-3">
        <div class="row mb-4">
            <div class="col-md-4">
                <div class="widget widget-light pb-2 mb-4">
                    <h4 class="widget-title">Contacts</h4>
                    <ul>
                        <li><a class="widget-link" href="mailto:support@example.com"><i class="ai-mail fs-lg me-2"></i>contacts@pernova.io</a></li>
<!--                        <li><a class="widget-link" href="tel:9107848015"><i class="ai-phone fs-lg me-2"></i>910-784-8015</a></li>-->
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget widget-light pb-2 mb-4">
                    <h4 class="widget-title">Follow</h4><a class="btn-social bs-outline bs-lg bs-light bs-facebook me-2" href="#"><i class="ai-facebook"></i></a><a class="btn-social bs-outline bs-lg bs-light bs-twitter me-2" href="#"><i class="ai-twitter"></i></a><a class="btn-social bs-outline bs-lg bs-light bs-instagram me-2" href="#"><i class="ai-instagram"></i></a><a class="btn-social bs-outline bs-lg bs-light bs-pinterest" href="#"><i class="ai-pinterest"></i></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget widget-light pb-3 mb-4">
                    <h4 class="widget-title">Subscribe and never miss a post!</h4>
                    <form class="subscription-form validate" action="https://studio.us12.list-manage.com/subscribe/post?u=c7103e2c981361a6639545bd5&amp;amp;id=29ca296126" method="post" name="mc-embedded-subscribe-form" target="_blank" novalidate>
                        <div class="input-group flex-nowrap"><i class="ai-mail position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
                            <input class="form-control rounded-start" type="email" name="EMAIL" placeholder="Your email" required>
                            <button class="btn btn-primary" type="submit" name="subscribe">Subscribe*</button>
                        </div>
                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div style="position: absolute; left: -5000px;" aria-hidden="true">
                            <input class="subscription-form-antispam" type="text" name="b_c7103e2c981361a6639545bd5_29ca296126" tabindex="-1">
                        </div>
                        <div class="form-text">*Subscribe to our newsletter to receive early discount offers, updates and new products info.</div>
                        <div class="subscription-status"></div>
                    </form>
                </div>
            </div>
        </div>
<!--        <p class="fs-sm mb-3 order-md-1"><span class="text-light opacity-50 me-1">&copy; All rights reserved. Made by</span><a class="nav-link-style nav-link-light" href="https://createx.studio/" target="_blank" rel="noopener">Createx Studio</a></p>-->
    </div>
</footer>

templates/frontend/components/navbar.html
{% url 'index' as home %}


<!-- Navbar (Solid background + shadow)-->
<!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page.-->
<header class="header navbar navbar-expand-lg navbar-light bg-light navbar-shadow navbar-sticky" data-scroll-header>
    <div class="container px-0 px-xl-3">
        <button class="navbar-toggler ms-n2 me-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#primaryMenu"><span class="navbar-toggler-icon"></span></button><a class="navbar-brand flex-shrink-0 order-lg-1 mx-auto ms-lg-0 pe-lg-2 me-lg-4" href="{{ home }}"><img class="d-none d-lg-block" src="/static/img/logo/logo-dark.png" alt="CapLink" width="153"><img class="d-lg-none" src="/static/img/logo/logo-icon.png" alt="CapLink" width="58"></a>
        <div class="d-flex align-items-center order-lg-3 ms-lg-auto">
            <div class="d-lg-block d-none border-start me-4" style="height: 30px;"></div>
            <div class="d-lg-block d-none text-nowrap"><a class="btn-social bs-outline bs-twitter me-2" href="#"><i class="ai-twitter"></i></a><a class="btn-social bs-outline bs-facebook me-2" href="#"><i class="ai-youtube"></i></a><a class="btn-social bs-outline bs-instagram me-2" href="#"><i class="ai-telegram"></i></a></div>
        </div>
        {% if not request.user.is_authenticated %}
            <div class="d-flex align-items-center order-lg-3 ms-lg-auto" style="padding-left: 30px"><a class="nav-link-style fs-sm text-nowrap" href="#modal-signin" data-bs-toggle="modal" data-view="#modal-signin-view"><i class="ai-user fs-xl me-2"></i>Sign in</a><a class="btn btn-primary ms-grid-gutter d-none d-lg-inline-block" href="#modal-signin" data-bs-toggle="modal" data-view="#modal-signup-view">Sign up</a></div>
        {% else %}
            <div class="d-flex align-items-center order-lg-3 ms-lg-auto">
                <div class="navbar-tool dropdown"><a class="navbar-tool-icon-box" href=""><img class="navbar-tool-icon-box-img" src="/static/img/dashboard/avatar/main-sm.jpg" alt="Avatar"></a><a class="navbar-tool-label dropdown-toggle" href="{{ home }}"><small>Hello,</small>{{ request.user.username }}</a>
                    <ul class="dropdown-menu dropdown-menu-end" style="width: 15rem;">
                        <li><a class="dropdown-item d-flex align-items-center" href="{% url 'user:dashboard' %}"><i class="ai-home fs-base opacity-60 me-2"></i>Dashboard</a></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="{% url 'user:identitycertification' %}"><i class="ai-shopping-bag fs-base opacity-60 me-2"></i>Identity Certification</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="{% url 'user:logout' %}"><i class="ai-log-out fs-base opacity-60 me-2"></i>Sign out</a></li>
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="offcanvas offcanvas-collapse order-lg-2" id="primaryMenu">
            <div class="offcanvas-header navbar-shadow">
                <h5 class="mt-1 mb-0">Menu</h5>
                <button class="btn-close lead" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <!-- Menu-->
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{{ home }}">Home</a>
                    </li>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Games</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'games:game-list' %}">List of Games</a></li>
                            <li><a class="dropdown-item" href="">NFT Marketplace</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="https://mirror.xyz">Blogs</a>
                    </li>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Company</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'contact:about' %}">About us</a></li>
                            <li><a class="dropdown-item" href="{% url 'contact:contact' %}">Contact us</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="offcanvas-footer justify-content-center border-top"><a class="btn-social bs-lg bs-outline bs-facebook me-3" href="#"><i class="ai-facebook"></i></a><a class="btn-social bs-lg bs-outline bs-twitter me-3" href="#"><i class="ai-twitter"></i></a><a class="btn-social bs-lg bs-outline bs-instagram me-3" href="#"><i class="ai-instagram"></i></a><a class="btn-social bs-lg bs-outline bs-pinterest" href="#"><i class="ai-pinterest"></i></a></div>
        </div>
    </div>
</header>

templates/frontend/components/sidebar.html
<div class="col-lg-4 mb-4 mb-lg-0">
    <div class="bg-light rounded-3 shadow-lg">
        <div class="px-4 py-4 mb-1 text-center"><img class="d-block rounded-circle mx-auto my-2" src="/static/img/dashboard/avatar/main.jpg" at="Amanda Wilson" width="110">
            <h6 class="mb-0 pt-1">{{ request.user }}</h6>
        </div>
        <div class="d-lg-none px-4 pb-4 text-center"><a class="btn btn-primary px-5 mb-2" href="#account-menu" data-bs-toggle="collapse"><i class="ai-menu me-2"></i>Account menu</a></div>
        <div class="d-lg-block collapse pb-2" id="account-menu">
            <h3 class="d-block bg-secondary fs-sm fw-semibold text-muted mb-0 px-4 py-3">Dashboard</h3><a class="d-flex align-items-center nav-link-style px-4 py-3" href="{% url 'user:dashboard' %}"><i class="ai-shopping-bag fs-lg opacity-60 me-2"></i>Profile<span class="nav-indicator"></span><span class="text-muted fs-sm fw-normal ms-auto">2</span></a>
            <a class="d-flex align-items-center nav-link-style px-4 py-3" href="{% url "user:identitycertification" %}"><i class="ai-alert-circle opacity-60 me-2"></i> Identity Certification</a>
            <div class="d-flex align-items-center border-top">
            </div><a class="d-flex align-items-center nav-link-style px-4 py-3 border-top" href="{% url 'user:logout' %}"><i class="ai-log-out fs-lg opacity-60 me-2"></i>Sign out</a>
        </div>
    </div>
</div>

templates/frontend/components/sign-in-modal.html
<div class="modal fade" id="modal-signin" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="view show" id="modal-signin-view">
                <div class="modal-header border-0 bg-dark px-4">
                    <h4 class="modal-title text-light">Sign in</h4>
                    <button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="btn-close "></button>
                </div>
                <div class="modal-body px-4">
                    <p class="fs-ms text-muted">Sign in to your account using email and password provided during registration.</p>
                    <div id="login-form-msg">

                    </div>
                    <form class="needs-validation" novalidate action="{% url 'user:login' %}" id="login-form" onsubmit="loginSubmit();return false">{% csrf_token %}
                        <div class="mb-3">
                            <div class="input-group"><i class="ai-mail position-absolute top-50 start-0 translate-middle-y ms-3"></i>
                                <input class="form-control rounded" type="text" placeholder="Username" required name="username">
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="input-group"><i class="ai-lock position-absolute top-50 start-0 translate-middle-y ms-3"></i>
                                <div class="password-toggle w-100">
                                    <input class="form-control" type="password" placeholder="Password" required name="password">
                                    <label class="password-toggle-btn" aria-label="Show/hide password">
                                        <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-3 mb-3">
                            <div class="form-check">
                            </div><a class="nav-link-style fs-ms" href="password-recovery.html">Forgot password?</a>
                        </div>
                        <button class="btn btn-primary d-block w-100" type="submit">Sign in</button>
                        <p class="fs-sm pt-3 mb-0">Don't have an account? <a href='#' class='fw-medium' data-view='#modal-signup-view'>Sign up</a></p>
                    </form>
                </div>
            </div>
            <div class="view" id="modal-signup-view">
                <div class="modal-header border-0 bg-dark px-4">
                    <h4 class="modal-title text-light">Sign up</h4>
                    <button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="btn-close"></button>
                </div>
                <div class="modal-body px-4">
                    <p class="fs-ms text-muted">Registration takes less than a minute but gives you full control over your orders.</p>
                    <div id="register-form-msg">

                    </div>
                    <form class="needs-validation" novalidate action="" id="sign-up-form" onsubmit="registerSubmit(this);return false">{% csrf_token %}
                        <div class="mb-3">
                            <input class="form-control" type="text" placeholder="Full name" required name="fullname">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="text" placeholder="Username" required name="username">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="text" placeholder="Email" required name="email">
                        </div>
                        <div class="mb-3 password-toggle">
                            <input class="form-control" type="password" placeholder="Password" required name="password">
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                            </label>
                        </div>
                        <div class="mb-3 password-toggle">
                            <input class="form-control" type="password" placeholder="Confirm password" required name="password1">
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                            </label>
                        </div>
                        <button class="btn btn-primary d-block w-100" type="submit">Sign up</button>
                        <p class="fs-sm pt-3 mb-0">Already have an account? <a href='#' class='fw-medium' data-view='#modal-signin-view'>Sign in</a></p>
                    </form>
                </div>
            </div>
            <div class="modal-body text-center px-4 pt-2 pb-4">
                <hr class="my-0">
                <p class="fs-sm fw-medium text-heading pt-4">Or sign in with</p><a class="btn-social bs-facebook bs-lg mx-1 mb-2" href="#"><i class="ai-facebook"></i></a><a class="btn-social bs-twitter bs-lg mx-1 mb-2" href="#"><i class="ai-twitter"></i></a><a class="btn-social bs-instagram bs-lg mx-1 mb-2" href="#"><i class="ai-instagram"></i></a><a class="btn-social bs-google bs-lg mx-1 mb-2" href="#"><i class="ai-google"></i></a>
            </div>
        </div>
    </div>
</div>